/**
 * BL0CKS Heat System
 * 
 * Global escalation pressure. The walls always close in.
 * 
 * From GDD §4.10:
 * - Starts at 0 per Act, carries across levels within Act
 * - +1 every turn (auto), +1 per War, +1 per territory lost, +2 per police event
 * - -1 per Peace, -1 per Ghost, -2 per level complete
 * - Cap: 20 per Act. At 20 → Federal Indictment
 * 
 * Thresholds apply permanent global modifiers.
 */

/** Maximum heat before Federal Indictment */
export const HEAT_CAP = 20;

/**
 * Heat thresholds and their modifier effects.
 */
export const HEAT_THRESHOLDS = Object.freeze([
  {
    id: 'low',
    name: 'Low Heat',
    range: [0, 4],
    modifier: null,
    flavor: "Nobody's watching. Move freely.",
  },
  {
    id: 'warm',
    name: 'Warm',
    range: [5, 8],
    modifier: { peopleCostIncrease: 1 },
    flavor: "Undercovers are multiplying. Every move gets noticed.",
  },
  {
    id: 'hot',
    name: 'Hot',
    range: [9, 13],
    modifier: {
      peopleCostIncrease: 1,
      dualWhispers: true,
      statusCardInjectionInterval: 2,
    },
    flavor: "Corner boys are getting picked up. The block is paranoid.",
  },
  {
    id: 'on_fire',
    name: 'On Fire',
    range: [14, 17],
    modifier: {
      peopleCostIncrease: 1,
      dualWhispers: true,
      statusCardInjectionInterval: 2,
      intelCostDouble: true,
      loyaltyDecayPerTurn: 1,
    },
    flavor: "Everybody's a liability. One phone call from folding.",
  },
  {
    id: 'federal',
    name: 'Federal',
    range: [18, 20],
    modifier: {
      peopleCostIncrease: 1,
      dualWhispers: true,
      statusCardInjectionInterval: 2,
      intelCostDouble: true,
      loyaltyDecayPerTurn: 1,
      federalIndictment: true,
      turnsToComplete: 3,
    },
    flavor: "The feds have the wiretap transcripts. Move NOW or it's over.",
  },
]);

/**
 * Get the current heat threshold based on heat level.
 * @param {number} heat
 * @returns {object} Threshold object
 */
export function getHeatThreshold(heat) {
  const clamped = Math.max(0, Math.min(heat, HEAT_CAP));
  for (const threshold of HEAT_THRESHOLDS) {
    if (clamped >= threshold.range[0] && clamped <= threshold.range[1]) {
      return threshold;
    }
  }
  return HEAT_THRESHOLDS[HEAT_THRESHOLDS.length - 1];
}

/**
 * Increase heat by a specified amount.
 * @param {object} state - Current game state
 * @param {number} amount - Heat to add
 * @param {string} source - Why heat increased (for events)
 * @returns {{ heat: number, thresholdCrossed: object|null, _heatSource: string }}
 */
export function increaseHeat(state, amount, source = 'unknown') {
  const oldHeat = state.heat || 0;
  const newHeat = Math.min(oldHeat + amount, HEAT_CAP);

  const oldThreshold = getHeatThreshold(oldHeat);
  const newThreshold = getHeatThreshold(newHeat);

  const crossed = oldThreshold.id !== newThreshold.id ? newThreshold : null;

  return {
    heat: newHeat,
    thresholdCrossed: crossed,
    _heatSource: source,
  };
}

/**
 * Decrease heat by a specified amount.
 * @param {object} state - Current game state
 * @param {number} amount - Heat to remove
 * @param {string} source - Why heat decreased
 * @returns {{ heat: number, _heatSource: string }}
 */
export function decreaseHeat(state, amount, source = 'unknown') {
  const newHeat = Math.max((state.heat || 0) - amount, 0);
  return { heat: newHeat, _heatSource: source };
}

/**
 * Auto-increment heat at Heat Check phase (+1 per turn).
 * @param {object} state
 * @returns {object} Heat patch
 */
export function heatCheckPhase(state) {
  return increaseHeat(state, 1, 'turn_auto');
}

/**
 * Get all active heat modifiers for the current heat level.
 * @param {number} heat
 * @returns {object} Combined modifier object
 */
export function getActiveModifiers(heat) {
  const threshold = getHeatThreshold(heat);
  return threshold.modifier || {};
}

/**
 * Check if Federal Indictment is active.
 * @param {number} heat
 * @returns {boolean}
 */
export function isFederalIndictment(heat) {
  return heat >= 18;
}

/**
 * Calculate heat generated by a specific action.
 * @param {string} action - Action type ('war', 'territory_lost', 'police_event', 'peace', 'ghost')
 * @returns {number} Heat delta (positive = increase, negative = decrease)
 */
export function getHeatForAction(action) {
  const heatMap = {
    war: 1,
    war_blitz: 2,        // Powered War generates +2
    territory_lost: 1,
    police_event: 2,
    peace: -1,
    ghost: -1,
    level_complete: -2,
  };
  return heatMap[action] ?? 0;
}
